version: "3"

services: 
  web: 
    container_name: demorest
    restart: always
    build: .
    ports:
    - "5000:3000"
    links:
      - mongo
      - rabbitmq
    volumes:
      - .:/app
  mongo:
    container_name: mydb
    image: mongo
    ports: 
      - "27018:27017"
    logging:
      driver: none
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672